export interface ClinicalScenario {
  id: string;
  category: "neurology" | "cardiovascular" | "pediatrics" | "general" | "administrative";
  label: string;
  text: string;
  isBargeIn: boolean;
  expectedTriage: "emergency" | "priority" | "routine";
  expectedEsi: number;
  description: string;
}

export const CLINICAL_VERIFICATION_SCENARIOS: ClinicalScenario[] = [
  {
    id: "scen-01",
    category: "neurology",
    label: "Stroke Presentation",
    text: "My wife noticed my right face is drooping, my right arm is weak and I have trouble getting my words out.",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 2,
    description: "Acute BE-FAST ischemic stroke presentation requiring immediate hospital evaluation.",
  },
  {
    id: "scen-02",
    category: "neurology",
    label: "Transient Improvement (TIA)",
    text: "But it's just like it came for 5 mins and now I feel better?",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 2,
    description: "Transient ischemic attack with spontaneous symptom resolution; must not be downplayed.",
  },
  {
    id: "scen-03",
    category: "general",
    label: "Financial Hardship",
    text: "Well I am poor.. i cant afford all that..",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 2,
    description: "Patient expressing financial distress; verifies routing recommends public/subsidized facilities without clinical downplay.",
  },
  {
    id: "scen-04",
    category: "general",
    label: "Outskirts / Remote",
    text: "I am at outskirts with no hospitals closeby :)",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 2,
    description: "Remote location constraint requiring ambulance dispatch and realistic travel time routing.",
  },
  {
    id: "scen-05",
    category: "general",
    label: "Mild Elbow Ache (Non-Emergent)",
    text: "I have a slight ache in my elbow.",
    isBargeIn: false,
    expectedTriage: "routine",
    expectedEsi: 4,
    description: "Mild musculoskeletal pain without red flags.",
  },
  {
    id: "scen-06",
    category: "cardiovascular",
    label: "Intake: Chest Tightness",
    text: "I've been feeling an uncomfortable tightness in my chest.",
    isBargeIn: false,
    expectedTriage: "priority",
    expectedEsi: 3,
    description: "Undifferentiated chest discomfort requiring targeted characterization.",
  },
  {
    id: "scen-07",
    category: "cardiovascular",
    label: "Intake: 20m + At Rest",
    text: "It started about twenty minutes ago while I was sitting down.",
    isBargeIn: false,
    expectedTriage: "priority",
    expectedEsi: 3,
    description: "Rest-onset chest discomfort progressing towards unstable angina / ACS evaluation.",
  },
  {
    id: "scen-08",
    category: "cardiovascular",
    label: "Intake: 'Well to my head actually'",
    text: "Well to my head actually.",
    isBargeIn: false,
    expectedTriage: "priority",
    expectedEsi: 3,
    description: "Atypical radiation to head/jaw; prompts clinical arbiter review.",
  },
  {
    id: "scen-09",
    category: "general",
    label: "Intake: 'I said head?' (No Loop)",
    text: "I said head?",
    isBargeIn: false,
    expectedTriage: "priority",
    expectedEsi: 3,
    description: "Verification of conversational manager avoiding repetitive question loops.",
  },
  {
    id: "scen-10",
    category: "neurology",
    label: "Emergency Stroke Interruption (Barge-In)",
    text: "Wait doctor! My face just started drooping and I can't lift my left arm!",
    isBargeIn: true,
    expectedTriage: "emergency",
    expectedEsi: 1,
    description: "Urgent mid-speech barge-in override interrupting lead physician speech.",
  },
  {
    id: "scen-11",
    category: "cardiovascular",
    label: "Immediate Cardio Shock (ACS)",
    text: "I've had crushing pressure in the center of my chest for thirty minutes radiating into my left arm with cold sweats.",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 2,
    description: "Classic high-risk acute coronary syndrome presentation with diaphoresis and radiation.",
  },
  {
    id: "scen-12",
    category: "neurology",
    label: "Acute Stroke Deficit",
    text: "My wife noticed my right face is drooping, my right arm is weak and I have trouble getting my words out.",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 2,
    description: "Severe focal neurological deficits requiring emergency neurovascular intervention.",
  },
  {
    id: "scen-13",
    category: "cardiovascular",
    label: "Dual-Threat Cardioneuro",
    text: "I have sudden severe chest tightness, my left arm is numb, and I felt like I was going to black out with dizziness.",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 2,
    description: "Simultaneous hemodynamic and neurological compromise triggering multi-specialist consensus.",
  },
  {
    id: "scen-14",
    category: "pediatrics",
    label: "Pediatric Sepsis",
    text: "My 7-week-old newborn has a rectal temperature of 102.5 and is unusually floppy, grunting, and refusing to wake up to feed.",
    isBargeIn: false,
    expectedTriage: "emergency",
    expectedEsi: 1,
    description: "Neonatal fever with lethargy and respiratory grunting indicating life-threatening pediatric sepsis.",
  },
  {
    id: "scen-15",
    category: "administrative",
    label: "Routine Refill",
    text: "I am feeling completely fine and just need a prescription refill for my maintenance lisinopril 10mg.",
    isBargeIn: false,
    expectedTriage: "routine",
    expectedEsi: 5,
    description: "Asymptomatic medication refill request with zero emergency indicators.",
  },
];
